### ISSUE TITLE
clean target doesn't seem to remove latexmk generated files

### ISSUE THREAD

**Issue by eintw1ck** [dokempf/UseLatexMk#1]
Building after a cmake change wont update the latex target. Could this be a missing custom_target somewhere? I don't know much about how cmake tracks 'clean' dependencies.

**Comment by dokempf** [comment]
I havn't had a look into  `make clean` so far (not really part of my workflow), but as I see it this can be implemented by parsing the resulting `fls` files for output files and add them to the CMake property `ADDITIONAL_MAKE_CLEAN_FILES`. I will have a look.

I cannot reproduce your second issue with cmake changes. Can you open a second issue with steps to reproduce the problem?

**Comment by eintw1ck** [comment]
> Could this be a missing custom_target somewhere? I don't know much about how cmake tracks
> 'clean' dependencies.

I meant 'is this an issue with how you're registering targets in `add_latex_document`', it's not a separate issue. This is just a suggestion of what I suspect is going on, but I actually have no idea. :)

**Comment by dokempf** [comment]
Thinking about this a bit further I come to conclusion: This is not even possible to implement, because of the `clean` target not being a first class member in CMake. What I can easily do however, is adding a `clean_latex` target, that does latex cleaning, just how Brad King recommends in [this discussion](http://cmake.3232098.n2.nabble.com/Adding-dependencies-to-the-clean-target-in-2016-td7594696.html). Would that serve your purpose?

**Comment by eintw1ck** [comment]
On Wed, Feb 07, 2018 at 07:19:33AM -0800, dokempf wrote:
> Thinking about this a bit further I come to conclusion: This is not even possible to implement, because of the `clean` target not being a first class member in CMake. What I can easily do however, is adding a `clean_latex` target, that does latex cleaning, just how Brad King recommends in [this discussion](http://cmake.3232098.n2.nabble.com/Adding-dependencies-to-the-clean-target-in-2016-td7594696.html). Would that serve your purpose?
> 

That is unfortunate, a `clean_latex` target sounds an acceptable solution.

**Comment by dokempf** [comment]
A `clean_latex` target is now implemented on master. Also, for each target a target with _clean appended exists, that does the cleaning of that target. Internally, it relies on the -C option of latexmk. Please report any issues you find with it.
