### ISSUE TITLE
Setting openout_any does not work

### ISSUE THREAD

**Issue by mpauly** [dokempf/UseLatexMk#6]
Hi, 
when trying to compile the dune pdelabs tutorial I ran into a problem with the build process: 
I need to set `openout_any` to `a` for bibtex to work. In principle [these lines](https://github.com/dokempf/UseLatexMk/blob/7647e2fecf7df2807226bd6e5c06331ae516bc34/UseLatexMk.cmake#L212) are expected to do that. However, these lines did not work for me. During build bibtex reported that `openout_any` was `p` instead of `a`.

This is also what I would expect: if I understand correctly what cmake is doing, then `set()` just sets environment variables during the configuration step, but not during the actual build. That would mean that setting the environment variable via `set()` should not be possible, see also [this stackoverflow](https://stackoverflow.com/questions/35029277/how-to-modify-environment-variables-passed-to-custom-cmake-target).

I am not sure how to fix this in a sustainable way. I hot-fixed the problem by changing [this line](https://github.com/dokempf/UseLatexMk/blob/7647e2fecf7df2807226bd6e5c06331ae516bc34/UseLatexMk.cmake#L222) to `COMMAND env openout_any="a" ${LATEXMK_EXECUTABLE} ${LATEXMKRC_OPTIONS} ${LMK_SOURCE}`.

System: Fedora with the version `4.70b` of latexmk

**Comment by dokempf** [comment]
Thanks for the bug report and sorry for letting you wait so long. I have pushed a fix to #7 . It is basically your hot fix with `env` replaced by the portable version `${CMAKE_COMMAND} -E env`.
